version: "3"

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/templates/default.conf.template
      - ./static/:/static
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    environment:
      - URL
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
    restart: always
  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    environment:
      - URL
      - DEV_MAIL
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  postgresdb:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - ./postgres/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    container_name: web
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    environment:
      - URL
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - DEBUG
      - SECRET_KEY
    depends_on:
      - postgresdb
    ports:
      - "8000:8000"
  parsing:
    container_name: parsing
    build: 
      context: ./parsing
      dockerfile: Dockerfile
    volumes:
      - ./parsing:/usr/src/app
      - ./logs:/usr/src/app/logs
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    depends_on:
      - postgresdb