version: "3"

services:
  postgresdb:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=As3Vdsd898
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    depends_on:
      - postgresdb
    ports:
      - "8000:8000"
  parsing_ezugi_roulette:
    build:
      context: ./parsing
      dockerfile: ./docker/ezugi_roulette/Dockerfile
    volumes:
      - ./parsing:/usr/src/app
      - ./logs:/usr/src/app/logs
    depends_on:
      - postgresdb
