version: "3"

services:
  postgresdb:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - ./postgres/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    container_name: web
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    environment:
      - URL
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - DEBUG
      - SECRET_KEY
      - PAY_ID
      - PAY_SECRET1
      - PAY_SECRET2
    depends_on:
      - postgresdb
    ports:
      - "8000:8000"
  parsing:
    container_name: parsing
    build: 
      context: ./parsing
      dockerfile: Dockerfile
    volumes:
      - ./parsing:/usr/src/app
      - ./logs:/usr/src/app/logs
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    depends_on:
      - postgresdb