# Generated by Django 3.2.3 on 2021-09-19 13:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_partner', models.BooleanField(default=False)),
                ('login', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('usr_telegram', models.CharField(blank=True, max_length=20)),
                ('pro_time', models.DateTimeField()),
                ('tlg_id', models.CharField(blank=True, max_length=20)),
                ('online_time_sec', models.IntegerField(default=0)),
                ('referrer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Baccarat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bacc_id', models.CharField(max_length=30)),
                ('provider', models.CharField(default='Evolution', max_length=30)),
                ('stats', models.JSONField(blank=True, null=True)),
                ('game_state', models.CharField(blank=True, max_length=120)),
                ('sort_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BaccRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rule_type', models.IntegerField()),
                ('count', models.IntegerField()),
                ('color', models.IntegerField()),
                ('is_tg_on', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('price_day', models.IntegerField(default=1000)),
                ('price_week', models.IntegerField(default=5000)),
                ('price_month', models.IntegerField(default=15000)),
                ('site_msg', models.CharField(blank=True, max_length=255)),
                ('free_rouls_available', models.IntegerField()),
                ('free_rules_available', models.IntegerField()),
                ('min_chances', models.IntegerField()),
                ('min_columns_and_dozens', models.IntegerField()),
                ('min_alts', models.IntegerField()),
                ('min_sectors', models.IntegerField()),
                ('min_sectors_3', models.IntegerField()),
                ('min_sectors_6', models.IntegerField()),
                ('min_numbers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ParseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('evo_id', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, unique=True)),
                ('free_days', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Roulette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('roul_id', models.IntegerField()),
                ('new_stats', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_in_row', models.BooleanField()),
                ('rule_type', models.IntegerField()),
                ('how_many_in_row', models.IntegerField()),
                ('color', models.IntegerField()),
                ('is_tg_on', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TlgBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_token', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_zero', models.JSONField(default={'alt_dozen_column': 0, 'alt_fifty_fifty': 0, 'dozen_column': 0, 'fifty_fifty': 0})),
                ('checked_nums', models.JSONField(blank=True, default=[])),
                ('show_nums_count', models.IntegerField(default=100)),
                ('individual_stats', models.JSONField(blank=True, default={})),
                ('curr_baccarats', models.ManyToManyField(blank=True, null=True, to='main.Baccarat')),
                ('curr_roulettes', models.ManyToManyField(blank=True, null=True, to='main.Roulette')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TlgMsgBacc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sended', models.BooleanField(default=False)),
                ('bacc_name', models.CharField(max_length=40)),
                ('rule_name', models.CharField(max_length=20)),
                ('count', models.IntegerField()),
                ('is_stoped', models.BooleanField(default=False)),
                ('msg_id', models.IntegerField(default=-1)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.baccrule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TlgMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sended', models.BooleanField(default=False)),
                ('roul_name', models.CharField(max_length=40)),
                ('is_in_order', models.BooleanField()),
                ('rule_name', models.CharField(max_length=20)),
                ('count', models.IntegerField()),
                ('is_stoped', models.BooleanField(default=False)),
                ('msg_id', models.IntegerField(default=-1)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.rule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RefLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, unique=True)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.promo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.IntegerField()),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_current', models.IntegerField(default=0)),
                ('balance_wait', models.IntegerField(default=0)),
                ('balance_paid', models.IntegerField(default=0)),
                ('percent', models.IntegerField(default=25, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('curr_promo', models.ManyToManyField(blank=True, null=True, to='main.Promo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('roulette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.roulette')),
            ],
        ),
        migrations.CreateModel(
            name='ClickEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=25, unique=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.reflink')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='referrer_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='main.reflink'),
        ),
        migrations.AddField(
            model_name='user',
            name='tlg_bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tlgbot'),
        ),
    ]
