# Generated by Django 3.1.7 on 2021-03-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tlg_bot',
            name='name',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tlgmsg',
            name='msg_id',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='tlg_bot',
            name='tg_token',
            field=models.CharField(max_length=30),
        ),
    ]
