# Generated by Django 3.2.3 on 2021-05-19 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RouletteInfo',
        ),
    ]
