# Generated by Django 3.1.7 on 2021-03-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210329_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tlgbot',
            name='tg_token',
            field=models.CharField(max_length=60),
        ),
    ]
