# Generated by Django 3.1.7 on 2021-03-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210329_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='tlgmsg',
            name='count',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tlgmsg',
            name='is_in_order',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tlgmsg',
            name='roul_name',
            field=models.CharField(default='Aga roul', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tlgmsg',
            name='rule_name',
            field=models.CharField(default='red', max_length=20),
            preserve_default=False,
        ),
    ]
