# Generated by Django 3.2.3 on 2021-05-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_parsedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='baccarat',
            name='game_state',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BaccGame',
        ),
    ]
