# Generated by Django 3.1.7 on 2021-03-30 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210330_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='is_tg_on',
            field=models.BooleanField(default=False),
        ),
    ]
