# Generated by Django 3.1.7 on 2021-03-31 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rule_is_tg_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tlgmsg',
            name='msg_id',
        ),
    ]
