# Generated by Django 3.2.3 on 2021-05-29 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_baccarat_game_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baccarat',
            name='game_state',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
