# Generated by Django 3.1.7 on 2021-03-31 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_tlgmsg_msg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tlgmsg',
            name='is_stoped',
            field=models.BooleanField(default=False),
        ),
    ]
