# Generated by Django 3.2.3 on 2021-06-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_baccrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='curr_baccarats',
            field=models.ManyToManyField(blank=True, null=True, to='main.Baccarat'),
        ),
    ]
