# Generated by Django 3.1.7 on 2021-04-06 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_tlgmsg_is_stoped'),
    ]

    operations = [
        migrations.AddField(
            model_name='tlgmsg',
            name='rule',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.rule'),
            preserve_default=False,
        ),
    ]
