# Generated by Django 3.2.3 on 2021-06-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_usersetting_curr_baccarats'),
    ]

    operations = [
        migrations.AddField(
            model_name='baccrule',
            name='color',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
