# Generated by Django 3.1.7 on 2021-04-10 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_tlgmsg_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tlg_bot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tlgbot'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tlg_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
