# Generated by Django 3.2.3 on 2021-06-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_baccrule_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='baccarat',
            name='sort_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
