# Generated by Django 3.2.3 on 2021-06-08 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_baccarat_sort_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TlgMsgBacc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sended', models.BooleanField(default=False)),
                ('bacc_name', models.CharField(max_length=40)),
                ('rule_name', models.CharField(max_length=20)),
                ('count', models.IntegerField()),
                ('is_stoped', models.BooleanField(default=False)),
                ('msg_id', models.IntegerField(default=-1)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.baccrule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
