# Generated by Django 3.1.7 on 2021-04-10 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210410_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='level',
        ),
        migrations.AddField(
            model_name='user',
            name='is_pro',
            field=models.BooleanField(default=False),
        ),
    ]
