# Generated by Django 3.1.7 on 2021-04-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210411_0102'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('free_rouls_available', models.IntegerField()),
                ('free_rules_available', models.IntegerField()),
                ('min_chances', models.IntegerField()),
                ('min_columns_and_dozens', models.IntegerField()),
                ('min_alts', models.IntegerField()),
                ('min_sectors', models.IntegerField()),
                ('min_sectors_3', models.IntegerField()),
                ('min_sectors_6', models.IntegerField()),
                ('min_numbers', models.IntegerField()),
            ],
        ),
    ]
