# Generated by Django 3.2.3 on 2021-08-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_reflink'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnersetting',
            name='all_time_pays',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partnersetting',
            name='balance',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partnersetting',
            name='clicks_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partnersetting',
            name='reg_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reflink',
            name='clicks_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reflink',
            name='promo',
            field=models.ManyToManyField(blank=True, null=True, to='main.Promo'),
        ),
        migrations.AddField(
            model_name='reflink',
            name='reg_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
