# Generated by Django 3.2.3 on 2021-08-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210812_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnersetting',
            name='all_time_pays',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='partnersetting',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='partnersetting',
            name='clicks_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='partnersetting',
            name='reg_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reflink',
            name='clicks_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reflink',
            name='reg_count',
            field=models.IntegerField(default=0),
        ),
    ]
