# Generated by Django 3.2.3 on 2021-08-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210817_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='free_days',
            field=models.IntegerField(default=0),
        ),
    ]
