# Generated by Django 3.2 on 2021-04-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_baccarat_baccgame'),
    ]

    operations = [
        migrations.AddField(
            model_name='baccarat',
            name='stats',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
