# Generated by Django 3.2 on 2021-04-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_baccarat_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='online_time_sec',
            field=models.IntegerField(default=0),
        ),
    ]
