# Generated by Django 3.2.3 on 2021-08-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_promo_free_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnersetting',
            name='curr_promo',
            field=models.ManyToManyField(blank=True, null=True, to='main.Baccarat'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='curr_roulettes',
            field=models.ManyToManyField(blank=True, null=True, to='main.Roulette'),
        ),
    ]
