# Generated by Django 3.2.3 on 2021-08-26 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_partnersetting_curr_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reflink',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.user'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='reflink',
            name='promo',
        ),
        migrations.AddField(
            model_name='reflink',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.promo'),
        ),
    ]
