# Generated by Django 3.2.3 on 2021-08-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20210826_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='reflink',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reflink',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
