# Generated by Django 3.2 on 2021-05-12 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_number_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='roulette',
            name='new_stats',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
