# Generated by Django 3.2.3 on 2021-08-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20210826_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reflink',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reflink',
            name='source',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
