# Generated by Django 3.2.3 on 2021-08-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20210826_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='value',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='reflink',
            name='value',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
