# Generated by Django 3.2.3 on 2021-08-28 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20210827_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referrer_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral', to='main.reflink'),
        ),
    ]
