# Generated by Django 3.2.3 on 2021-08-28 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_user_referrer_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referrer_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='main.reflink'),
        ),
    ]
