# Generated by Django 3.2.3 on 2021-08-31 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_user_referrer_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=25, unique=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.reflink')),
            ],
        ),
    ]
