# Generated by Django 3.2.3 on 2021-09-01 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_clickentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reflink',
            name='clicks_count',
        ),
        migrations.RemoveField(
            model_name='reflink',
            name='reg_count',
        ),
    ]
