# Generated by Django 3.2.3 on 2021-09-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsetting',
            name='price_day',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='globalsetting',
            name='price_month',
            field=models.IntegerField(default=15000),
        ),
        migrations.AddField(
            model_name='globalsetting',
            name='price_week',
            field=models.IntegerField(default=5000),
        ),
        migrations.AddField(
            model_name='globalsetting',
            name='site_msg',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
