# Generated by Django 3.2.3 on 2021-09-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_remove_user_is_pro'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='checked_nums',
            field=models.JSONField(default=[]),
        ),
    ]
