# Generated by Django 3.2.3 on 2021-09-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_usersetting_checked_nums'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='individul_stats',
            field=models.JSONField(default={}),
        ),
    ]
