# Generated by Django 3.2.3 on 2021-09-02 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_usersetting_individul_stats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersetting',
            old_name='individul_stats',
            new_name='individual_stats',
        ),
    ]
