# Generated by Django 3.2.3 on 2021-09-07 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_rename_individul_stats_usersetting_individual_stats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='number',
            name='is_new',
        ),
    ]
